
$('.shouye').click(function(){
	location.href='dengluhou.html';
})
$('.wenzhang').click(function(){
    location.href='publish.html';
})
$('.xiangfa').click(function(){
	location.href='idea.html';
})
$('.tongzhi').click(function(){
	location.href='notice.html';
})
$('.denglu').click(function(){
	location.href='Edit_my_profile.html';
})
$('.idea').click(function(){
	location.href='idea-1.html';
})
$('.xxxxx').click(function(){
	location.href='dengluhou.html';
})
$('.huati').click(function(){
	location.href='Add_topic.html';
})
